name: Delövning 1 - Minimal Pipeline

on:
  workflow_dispatch:

jobs:
  python-version-info:
    runs-on: ubuntu-latest

    steps:
      - name: Visa att pipelinen startat
        run: echo "Pipelinen har startat!"

      - name: Visa Python-version
        run: python --version
