name: Delövning 2 - Parallella och sekventiella jobb

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checka ut koden från repot
      uses: actions/checkout@v3
    
    - name: Lista filerna i repot
      run: ls -al
      

  print-message:
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - name: Meddelande
        run: echo "Detta körs efter list-files"