name: Delövning 3 - Artifacts
on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Skapar log.txt
        run: echo "Detta är logginnehållet. Testar artefakter i GitHub Actions." > log.txt
      
      - name: Laddar upp loggfilen som artifact
        uses: actions/upload-artifact@v4
        with:
          name: loggfil
          path: log.txt
